import type { SmashCharacter } from "@/lib/characters";

// Maps each fighter to its stock-icon file slug (public/characters/<slug>.png).
// Slugs are Nintendo's internal codenames, ripped from the game files — not
// the display name — hence the explicit table rather than a derived slug.
// Pyra/Mythra is one combined roster entry (players pick "Pyra/Mythra" as a
// single value), so it maps to one representative icon (Pyra's). Partial
// rather than a total map over SmashCharacter — "Random" has no real fighter
// art to rip, so it's deliberately left out and falls through to
// CharacterIcon's colored-initials badge instead.
export const CHARACTER_ICON_SLUGS: Partial<Record<SmashCharacter, string>> = {
  Mario: "mario",
  "Donkey Kong": "donkey",
  Link: "link",
  Samus: "samus",
  "Dark Samus": "samusd",
  Yoshi: "yoshi",
  Kirby: "kirby",
  Fox: "fox",
  Pikachu: "pikachu",
  Luigi: "luigi",
  Ness: "ness",
  "Captain Falcon": "captain",
  Jigglypuff: "purin",
  Peach: "peach",
  Daisy: "daisy",
  Bowser: "koopa",
  "Ice Climbers": "ice_climber",
  Sheik: "sheik",
  Zelda: "zelda",
  "Dr. Mario": "mariod",
  Pichu: "pichu",
  Falco: "falco",
  Marth: "marth",
  Lucina: "lucina",
  "Young Link": "younglink",
  Ganondorf: "ganon",
  Mewtwo: "mewtwo",
  Roy: "roy",
  Chrom: "chrom",
  "Mr. Game & Watch": "gamewatch",
  "Meta Knight": "metaknight",
  Pit: "pit",
  "Dark Pit": "pitb",
  "Zero Suit Samus": "szerosuit",
  Wario: "wario",
  Snake: "snake",
  Ike: "ike",
  "Pokémon Trainer": "ptrainer",
  "Diddy Kong": "diddy",
  Lucas: "lucas",
  Sonic: "sonic",
  "King Dedede": "dedede",
  Olimar: "pikmin",
  Lucario: "lucario",
  "R.O.B.": "robot",
  "Toon Link": "toonlink",
  Wolf: "wolf",
  Villager: "murabito",
  "Mega Man": "rockman",
  "Wii Fit Trainer": "wiifit",
  "Rosalina & Luma": "rosetta",
  "Little Mac": "littlemac",
  Greninja: "gekkouga",
  "Mii Brawler": "miifighter",
  "Mii Swordfighter": "miiswordsman",
  "Mii Gunner": "miigunner",
  Palutena: "palutena",
  "Pac-Man": "pacman",
  Robin: "reflet",
  Shulk: "shulk",
  "Bowser Jr.": "koopajr",
  "Duck Hunt": "duckhunt",
  Ryu: "ryu",
  Ken: "ken",
  Cloud: "cloud",
  Corrin: "kamui",
  Bayonetta: "bayonetta",
  Inkling: "inkling",
  Ridley: "ridley",
  Simon: "simon",
  Richter: "richter",
  "King K. Rool": "krool",
  Isabelle: "shizue",
  Incineroar: "gaogaen",
  "Piranha Plant": "packun",
  Joker: "jack",
  Hero: "brave",
  "Banjo & Kazooie": "buddy",
  Terry: "dolly",
  Byleth: "master",
  "Min Min": "tantan",
  Steve: "pickel",
  Sephiroth: "edge",
  "Pyra/Mythra": "eflame",
  Kazuya: "demon",
  Sora: "trail",
};

export function characterIconSlug(name: string): string | undefined {
  return (CHARACTER_ICON_SLUGS as Record<string, string>)[name];
}
