// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "node:fs";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Read env files in the same lookup order Next.js uses (.env.development.local,
// .env.local, .env.development, .env). dotenv treats an already-set process.env
// value as authoritative, so loading them in this order makes the first file to
// define a key win — i.e. the same file Next.js itself would have picked.
//
// This matters because `.env.development` is checked in pointing at the local
// Docker database, while `.env` is normally a copy of `.env.example` holding
// real (production Neon) credentials. Loading `.env` first, as this file used
// to, meant `npx prisma migrate dev` — the setup step in the README — ran
// against production while `next dev` talked to localhost.
//
// Deployments are unaffected: CI and Vercel inject DATABASE_URL into the
// process environment, and none of these files override a value that's already
// there. That's also why this matches the previous behavior in those
// environments, where `.env` doesn't exist at all and the fallback did the work.
// The existsSync guards only keep dotenv from logging a line for each file
// that isn't there — the order and the first-wins behavior are what matter.
for (const file of [".env.development.local", ".env.local", ".env.development", ".env"]) {
  if (existsSync(file)) config({ path: file });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
