-- CreateEnum
CREATE TYPE "RatingAlgorithm" AS ENUM ('ELO', 'GLICKO2');

-- AlterTable
ALTER TABLE "RatingHistory" ALTER COLUMN "ratingBefore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ratingAfter" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "delta" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "RatingMatch" ADD COLUMN     "player1RdAfter" DOUBLE PRECISION,
ADD COLUMN     "player1RdBefore" DOUBLE PRECISION,
ADD COLUMN     "player1VolatilityAfter" DOUBLE PRECISION,
ADD COLUMN     "player1VolatilityBefore" DOUBLE PRECISION,
ADD COLUMN     "player2RdAfter" DOUBLE PRECISION,
ADD COLUMN     "player2RdBefore" DOUBLE PRECISION,
ADD COLUMN     "player2VolatilityAfter" DOUBLE PRECISION,
ADD COLUMN     "player2VolatilityBefore" DOUBLE PRECISION,
ALTER COLUMN "player1RatingBefore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "player1RatingAfter" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "player2RatingBefore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "player2RatingAfter" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Season" ADD COLUMN     "algorithm" "RatingAlgorithm" NOT NULL DEFAULT 'ELO';

-- AlterTable
ALTER TABLE "SeasonStanding" ALTER COLUMN "finalRating" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "practiceRatingDeviation" DOUBLE PRECISION NOT NULL DEFAULT 350,
ADD COLUMN     "practiceRatingVolatility" DOUBLE PRECISION NOT NULL DEFAULT 0.06,
ADD COLUMN     "ratingDeviation" DOUBLE PRECISION NOT NULL DEFAULT 350,
ADD COLUMN     "ratingVolatility" DOUBLE PRECISION NOT NULL DEFAULT 0.06,
ALTER COLUMN "rating" SET DEFAULT 1500,
ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "practiceRating" SET DEFAULT 1500,
ALTER COLUMN "practiceRating" SET DATA TYPE DOUBLE PRECISION;
